export const plantData = [
    {
      "category": "Indoor Plants",
      "plants": [
        {
          "id": 1,
          "name": "Snake Plant",
          "price": 399,
          "rating": 5,
          "description": "The snake plant, also known as Sansevieria or Dracaena trifasciata, is a highly popular and resilient indoor plant admired for its tall, upright, sword-shaped leaves with striking green patterns and often yellow or white edges. Native to West Africa, it thrives in a wide range of indoor conditions and is particularly known for tolerating low light, dry air, and infrequent watering, making it ideal for beginners or busy lifestyles. Its bold, modern appearance adds a sculptural touch to any space, from homes to offices. Beyond its visual appeal, the snake plant is also praised for its air-purifying abilities—removing harmful toxins like formaldehyde and benzene—and is one of the few plants that convert CO₂ into oxygen at night, making it a great choice for bedrooms. Low-maintenance, stylish, and beneficial for health, the snake plant is a perfect addition to any indoor plant collection.",
          "qty" : 0,
          "image": ["https://m.media-amazon.com/images/I/61LjnhXXWIL.jpg", "https://m.media-amazon.com/images/I/517yfxsGChL.jpg", "https://m.media-amazon.com/images/I/61LFSt0+AfL._SL1024_.jpg"],
        },
        {
          "id": 2,
          "name": "Peace Lily",
          "price": 499,
          "rating": 3,
          "description": "The peace lily, or Spathiphyllum, is a graceful and elegant indoor plant known for its lush, dark green foliage and striking white flowers that resemble calla lilies. Native to tropical regions of the Americas and Southeast Asia, it thrives in indirect light and humid conditions, making it perfect for indoor environments. The peace lily is relatively low-maintenance, requiring only moderate watering and occasional misting to stay healthy and vibrant. Aside from its beauty, it is also highly valued for its air-purifying properties—removing pollutants such as ammonia, benzene, and formaldehyde from indoor air. Its ability to signal thirst by drooping slightly makes it easy even for beginner plant owners to care for. With its combination of aesthetic charm and environmental benefits, the peace lily is a popular choice for homes, offices, and places that could use a touch of natural serenity.",
          "qty" : 27,
          "image": ["https://seed2plant.in/cdn/shop/files/SPR-variegated-peace-lily-domino-7097188-hero-A-422d7faa152d42d3a4030ff8a2a33768.jpg", "https://exoticflora.in/cdn/shop/products/peacelily.jpg", "https://www.palasa.co.in/cdn/shop/articles/Blog_Cover_Image__17.jpg"],
        },
        {
          "id": 3,
          "name": "ZZ Plant",
          "price": 349,
          "rating": 4,
          "description": "The ZZ plant, or Zamioculcas zamiifolia, is a tough, low-maintenance indoor plant known for its thick, glossy, dark green leaves that grow in an elegant, upward arching pattern. Native to Eastern Africa, the ZZ plant is extremely drought-tolerant and can thrive in low to moderate light, making it ideal for homes, offices, and low-light corners where other plants may struggle. Its waxy leaves not only add a rich, tropical look but also help the plant retain moisture, allowing it to go weeks without water. The ZZ plant is also known for its air-purifying qualities, helping to remove toxins like xylene and toluene from indoor air. It’s resistant to most pests, requires very little attention, and can survive with minimal care, making it perfect for busy individuals or beginner plant enthusiasts. With its sculptural form and resilient nature, the ZZ plant brings a bold yet effortless greenery to any indoor space.",
          "qty" : 35,
          "image": ["https://myjungleclub.com/cdn/shop/files/Plants-265_zz.webp", "https://www.chhajedgarden.com/cdn/shop/files/robust-zz-plant-indoor_1043x1390.jpg", "https://i.etsystatic.com/22629375/r/il/20be79/3015581167/il_1588xN.3015581167_tk2z.jpg"],
        },
        {
          "id": 4,
          "name": "Spider Plant",
          "price": 259,
          "rating": 5,
          "description": "The spider plant, or Chlorophytum comosum, is a popular and easy-to-care-for houseplant known for its long, arching green leaves with white or yellow stripes and its charming baby “spiderettes” that dangle from the mother plant like little spiders on a web. Native to tropical and southern Africa, the spider plant thrives in bright, indirect light but is also tolerant of lower light conditions, making it a great choice for almost any indoor space. It’s fast-growing, adaptable, and forgiving—perfect for both beginners and experienced plant lovers. One of its standout features is its ability to purify indoor air, removing pollutants such as carbon monoxide, formaldehyde, and xylene. The spider plant is also non-toxic to pets, making it a safe and decorative addition to homes with animals. With its lively appearance, air-cleaning qualities, and minimal care needs, the spider plant remains a timeless favorite for bringing natural beauty and freshness indoors.",
          "qty" : 18,
          "image": ["https://m.media-amazon.com/images/I/61bfaK6hWpL.jpg", "https://www.ugaoo.com/cdn/shop/files/1_ec5c0b2a-34b6-4fd2-b95b-0775fc80d710.jpg", "https://plantshub.in/wp-content/uploads/2023/06/5b59a7f8-e644-477e-99b4-8fd8f0e24ebb-jpg.webp"],
        },
        {
          "id": 5,
          "name": "Fiddle Leaf Fig",
          "price": 799,
          "rating": 1,
          "description": "The fiddle leaf fig, or Ficus lyrata, is a striking indoor plant known for its large, glossy, violin-shaped leaves that can grow over a foot long and add a dramatic, sculptural presence to any room. Native to the tropical rainforests of West Africa, it thrives in bright, indirect light and prefers warm, stable environments with moderate humidity. While it can be a bit more finicky than other houseplants—sensitive to overwatering, drafts, and sudden changes in light—it rewards proper care with impressive growth and lush foliage. The fiddle leaf fig has become a favorite in modern interior design for its bold, architectural form and ability to serve as a natural focal point in living rooms, offices, or studios. Though it requires a bit more attention than hardier plants, its elegant appearance and ability to transform spaces make it a top choice for plant enthusiasts and home decorators alike.",
          "qty" : 0,
          "image": ["https://m.media-amazon.com/images/I/61EoMsA-wkL._SL1000_.jpg", "https://www.thetutuguru.com.au/wp-content/uploads/2024/07/Ficus-lyrata-Fiddle-Leaf-Fig-Tree-potted-indoors.jpg", "https://unlimitedgreens.com/cdn/shop/files/image-_17_e819834b-d056-4d16-95bf-55e768eea1ed.jpg"],
        },
        {
          "id": 6,
          "name": "Parlor Palm",
          "price": 289,
          "rating": 3,
          "description": "The parlor palm, or Chamaedorea elegans, is a classic indoor plant loved for its elegant, feathery fronds and easygoing nature. Native to the rainforests of Southern Mexico and Guatemala, it adapts well to indoor environments and thrives in low to moderate light, making it perfect for homes and offices. This slow-growing palm has slender green stems and soft arching leaves that bring a touch of tropical charm and natural calm to any space. The parlor palm is also one of the few true palms that can flourish indoors without direct sunlight, and it requires only occasional watering to stay healthy. In addition to its decorative appeal, it's non-toxic to pets and contributes to cleaner air by filtering out common indoor pollutants. With its low maintenance needs, compact size, and graceful appearance, the parlor palm remains a timeless favorite among both beginner and experienced plant lovers.",
          "qty" : 9,
          "image": ["https://nurserylive.com/cdn/shop/products/nurserylive-g-chamaedorea-elegans-parlour-palm-plant_600x600.jpg", "https://m.media-amazon.com/images/I/81hl3po0unL._SL1500_.jpg", "https://cdn.mos.cms.futurecdn.net/qcdYRNJMNAvPyqCpn8P6hS-1132-80.jpg.webp"],
        }
      ]
    },
    {
      "category": "Outdoor Plants",
      "plants": [
        {
          "id": 7,
          "name": "Bougainvillea",
          "price": 299,
          "rating": 1,
          "description": "Bougainvillea is a vibrant and eye-catching plant known for its explosion of colorful bracts that surround its tiny white flowers. Native to South America, particularly Brazil, Peru, and Argentina, this tropical vine thrives in warm, sunny environments and adds a burst of color to gardens, patios, and trellises. Bougainvillea's signature papery blooms come in a variety of vivid shades — including magenta, purple, orange, red, pink, and white — making it a favorite for dramatic landscaping. Though often grown outdoors in warmer climates, it can also be trained as a container plant or bonsai with proper pruning. Bougainvillea prefers full sun, well-draining soil, and minimal watering once established, making it a drought-tolerant choice for low-maintenance gardening. While not suitable for pet households due to its thorny stems and potential toxicity, it rewards growers with stunning seasonal displays and a fast-growing, climber-friendly nature that brings tropical flair to any space.",
          "qty" : 0,
          "image": ["https://www.gardeningexpress.co.uk/media/catalog/product/cache/fa4e57de89a0fb1427d2c82c53fb200f/b/o/bourgainvillea-tree-hires_2-7467d4c6.webp", "https://mediaserver.krishnanursery.in/3078-large_default/bougainvillea-pink-flower-plant.jpg", "https://eureka-farms.com/cdn/shop/files/BarbaraKarst7gal.jpg"],
        },
        {
          "id": 8,
          "name": "Areca Palm",
          "price": 599,
          "rating": 5,
          "description": "The Areca Palm, also known as Dypsis lutescens or butterfly palm, is a popular indoor plant cherished for its lush, feathery fronds and air-purifying abilities. Native to the tropical forests of Madagascar, this palm adds a breezy, tropical aesthetic to homes, offices, and shaded patios. Its graceful, arching green leaves grow in clusters from cane-like golden stems, giving it a full, bushy appearance that makes it an excellent natural screen or statement plant. The Areca Palm thrives in bright, indirect light and enjoys consistently moist but well-drained soil. It’s relatively low-maintenance and responds well to regular misting, which mimics its native humid environment. In addition to being non-toxic to pets, the Areca Palm is celebrated for its ability to filter indoor air and increase humidity levels, promoting a healthier living environment. With its refined beauty and gentle presence, it remains a top choice for both plant novices and seasoned indoor gardeners.",
          "qty" : 25,
          "image": ["https://leafy-life.com/wp-content/uploads/2020/12/4CHLUB020.png", "https://d3k81ch9hvuctc.cloudfront.net/company/T8EXmi/images/bba076ce-213d-4023-b9a8-7d1383f7effa.jpeg", "https://www.padmamnursery.com/cdn/shop/files/Areca-Palm-Silver-Planter-1200x1200-fff8ccef-cbf2-4e2c-b3af-8d0d61fc779a-_2.jpg"],
        },
        {
          "id": 9,
          "name": "Money Plant (Climber)",
          "price": 199,
          "rating": 3,
          "description": "The Money Plant (Climber), scientifically known as Epipremnum aureum, is a beloved houseplant prized for its heart-shaped leaves, trailing vines, and reputation for bringing good luck and prosperity. Native to the tropical forests of Southeast Asia, this hardy climber adapts effortlessly to a variety of indoor conditions, making it a favorite among beginner plant lovers and seasoned gardeners alike. Its vibrant green foliage — often marbled with shades of yellow or cream — adds a fresh, energetic vibe to shelves, hanging baskets, or wall-mounted trellises. The money plant thrives in bright, indirect light but is also tolerant of low-light spaces, and requires only occasional watering, making it perfect for busy households. As a natural air purifier, it helps remove common indoor toxins, promoting a healthier home environment. Though mildly toxic if ingested, it's generally safe with proper placement. Easy to grow, propagate, and train as a climber or trailer, the money plant remains a timeless symbol of vitality, wealth, and growth.",
          "qty" : 40,
          "image": ["https://m.media-amazon.com/images/I/71f3V0oitKL._SL1500_.jpg", "https://naturetouch.co.in/wp-content/uploads/2021/10/DSC_0478-scaled.jpg", "https://www.theplantcompany.co.nz/file/getimage/shop/jpg/lg/epipremnum-aureum.webp"],
        },
        {
          "id": 10,
          "name": "Jasmine",
          "price": 249,
          "rating": 4,
          "description": "Jasmine, a timeless favorite in gardens and homes, is cherished for its intoxicating fragrance and delicate star-shaped blossoms. Belonging to the Jasminum genus, this plant has several popular varieties, such as Jasminum sambac (Arabian Jasmine) and Jasminum officinale (Common Jasmine), each admired for their sweet-smelling blooms. Native to tropical and subtropical regions of Asia and the Mediterranean, Jasmine thrives in full to partial sunlight and well-drained soil. Whether grown as a climbing vine, shrub, or potted plant, its elegant white or pale pink flowers bloom profusely during warmer months, filling the air with a scent often used in perfumes and essential oils. Beyond its ornamental charm, Jasmine symbolizes love, purity, and spiritual connection in many cultures. While it needs regular watering during the growing season, it prefers slightly dry conditions in winter. With the right care, Jasmine brings not just beauty and fragrance to a space but also a serene, almost romantic atmosphere that soothes the senses and uplifts the spirit.",
          "qty" : 27,
          "image": ["https://thursd.com/storage/media/79859/white-jasmine-flowers-on-green-leaves.jpg", "https://ksartscollection.com/cdn/shop/files/ks-jasmin-mogra-plant-jasminum-plant.jpg", "https://vgrgardens.com/wp-content/uploads/2022/09/star-jasmine-colour-kakatan.png"],
        },
        {
          "id": 11,
          "name": "Curry Leaf Plant",
          "price": 179,
          "rating": 2,
          "description": "The Curry Leaf Plant, or Murraya koenigii, is a fragrant, fast-growing shrub cherished for its aromatic leaves that are essential in South Asian cooking. Native to India and Sri Lanka, this plant holds both culinary and cultural significance, often found growing in backyard gardens and kitchen windows. Its slender branches are lined with shiny, dark green leaflets that release a rich, spicy-citrus aroma when crushed. The curry leaf plant thrives in full sun and well-drained soil, flourishing in warm climates but also adapting well to containers that can be moved indoors during cooler months. In addition to its flavorful leaves, it occasionally produces small white flowers followed by purplish-black berries (non-edible), adding subtle beauty to its practical charm. Beyond the kitchen, the leaves are believed to have medicinal properties, supporting digestion and wellness in traditional remedies. Low-maintenance and deeply rooted in tradition, the curry leaf plant is both a symbol of homegrown goodness and a flavorful companion for any culinary enthusiast.",
          "qty" : 0,
          "image": ["https://images-cdn.ubuy.co.in/66775fa7228f560d99064e37-curry-trees-10-15cm.jpg", "https://spiceizright.com/wp-content/uploads/2021/05/20210707_082219-2.jpg", "https://exoticflora.in/cdn/shop/products/Murraya-koenigii-curry-tree.jpg"],
        },
        {
          "id": 12,
          "name": "Ashoka Tree",
          "price": 999,
          "rating": 1,
          "description": "The Ashoka Tree, scientifically known as Saraca asoca, is a revered and ornamental evergreen tree admired for its lush foliage, cascading clusters of orange-red flowers, and deep cultural significance. Native to the Indian subcontinent, it holds a sacred place in Indian mythology and is often associated with love, fertility, and spirituality. The tree's dense, spreading canopy is filled with soft, coppery-red new leaves that mature to glossy green, creating a vibrant contrast year-round. In spring, it bursts into a dramatic display of fragrant, flame-colored blooms that attract butterflies and add a festive charm to any landscape. The Ashoka Tree thrives in tropical to subtropical climates, preferring well-drained soil and a sunny to partially shaded location. Despite its majestic appearance, it's relatively low-maintenance and can be cultivated in gardens, temple grounds, or as an avenue tree. Beyond its beauty, the Ashoka Tree is also valued in Ayurveda for its bark, believed to support women’s health and overall wellness. With its elegance, symbolism, and ecological benefits, the Ashoka Tree is a timeless presence in both traditional and modern green spaces.",
          "qty" : 19,
          "image": ["https://m.media-amazon.com/images/I/81qeSO2fszL._SX679_.jpg", "https://nurserylive.com/cdn/shop/products/nurserylive-ashoka-tree-pendula-ashok-plant-1_455b9345-b6a4-4968-a88c-e4428d17c128-104219.jpg", "https://rukminim2.flixcart.com/image/832/832/xif0q/plant-sapling/y/n/1/perennial-no-yes-ashok-plant-6-1-pot-srijaplant-original-imagka6ejmwh6vvm.jpeg"],
        }
      ]
    },
    {
      "category": "Flowering Plants",
      "plants": [
        {
          "id": 13,
          "name": "Rose Plant",
          "price": 199,
          "rating": 5,
          "description": "The Rose Plant, belonging to the Rosa genus, is an iconic symbol of beauty, love, and elegance, treasured worldwide for its exquisite blooms and enchanting fragrance. Native to temperate regions of Asia and cultivated for thousands of years, roses come in a stunning variety of colors, sizes, and forms — from compact shrubs to climbing varieties that adorn trellises and fences. Each rose blossom, whether velvety red, soft pink, radiant yellow, or pure white, carries its own meaning and emotional expression. The plant thrives best in well-drained soil and full sunlight, with regular watering and seasonal pruning to encourage healthy growth and abundant flowering. While some varieties are fragrant and delicate, others are robust and nearly thornless, making them versatile for gardens, balconies, and floral arrangements. Beyond their ornamental value, roses are also used in perfumes, skincare, and even culinary creations like rose water and syrups. With timeless charm and deep symbolic roots, the rose plant continues to be a beloved choice for gardeners and romantics alike.",
          "qty" : 10,
          "image": ["https://puspitanursery.com/cdn/shop/products/91eSCsJ_1IL._SL1500.jpg", "https://puspitanursery.com/cdn/shop/products/61MFGftmcsS_1024x1024.jpg", "https://wildroots.in/wp-content/uploads/2020/10/tiger-rose.jpg"],
        },
        {
          "id": 14,
          "name": "Hibiscus",
          "price": 249,
          "rating": 5,
          "description": "The Hibiscus, known for its bold, trumpet-shaped blooms and tropical flair, is a vibrant flowering plant from the Hibiscus genus, celebrated for its striking appearance and versatility. Native to warm-temperate and tropical regions, hibiscus plants come in a wide range of colors — from fiery reds and sunny yellows to deep purples and pure whites — often blooming with dramatic flair against lush green foliage. Whether grown as a shrub, small tree, or potted ornamental, the hibiscus brings a burst of color to gardens, balconies, and courtyards. It thrives in full sunlight, well-drained soil, and responds well to regular watering, making it an ideal choice for tropical and subtropical climates. In addition to its decorative appeal, hibiscus holds cultural and medicinal value in many traditions — with Hibiscus rosa-sinensis revered in Indian worship rituals, and Hibiscus sabdariffa (Roselle) used in herbal teas and remedies. With its continuous blooms, easy care, and bold beauty, the hibiscus is both a garden centerpiece and a symbol of grace, vitality, and celebration.",
          "qty" : 0,
          "image": ["https://www.silverstonegardening.com.au/wp-content/uploads/2023/02/ksjdnbcj.png", "https://m.media-amazon.com/images/I/71LyL+e2VtL._SX679_.jpg", "https://dukaan.b-cdn.net/2000x2000/webp/upload_file_service/1c5c54ef-de1d-4709-a879-2761bdd2d944/38.png"],
        },
        {
          "id": 15,
          "name": "Marigold",
          "price": 149,
          "rating": 3,
          "description": "The Marigold, a cheerful and resilient flowering plant from the Tagetes genus, is celebrated for its vibrant blooms, symbolic significance, and pest-repelling properties. Native to the Americas but widely cultivated around the world, marigolds are instantly recognizable by their bright orange, yellow, and golden blossoms that radiate warmth and positivity. These hardy annuals thrive in full sun and well-drained soil, blooming generously from spring through fall with minimal care. Their ruffled petals and distinct aroma make them a staple in both ornamental gardening and cultural rituals — especially in Indian festivals like Diwali and during the Day of the Dead in Latin America. In addition to their festive appeal, marigolds are valued in companion planting for naturally deterring pests and attracting beneficial insects. Whether lining borders, filling flower beds, or adorning altars, the marigold brings beauty, tradition, and function together in one low-maintenance, high-impact plant.",
          "qty" : 18,
          "image": ["https://goldenhillsfarm.in/media/product_images/deep-orange.jpg", "https://organicbazar.net/cdn/shop/products/Untitled-design-2022-06-03T183509.107.jpg", "https://rukminim2.flixcart.com/image/832/832/xif0q/plant-sapling/t/x/m/perennial-yes-yes-marigold-plant-38-1-plastic-bag-roy-plant-rb-original-imagkrsbnjknxehz.jpeg"],
        },
        {
          "id": 16,
          "name": "Petunia",
          "price": 179,
          "rating": 3,
          "description": "The Petunia is a charming and colorful flowering plant known for its trumpet-shaped blooms and long-lasting beauty. Belonging to the Solanaceae family, petunias originate from South America and are widely appreciated for their ability to brighten up gardens, balconies, and hanging baskets with a cascade of vibrant color. Their flowers come in an array of hues — from soft pastels to deep purples, bright pinks, reds, whites, and even multi-toned patterns — making them a favorite among gardeners looking for visual impact. Petunias thrive in full sunlight, well-drained soil, and require regular watering to maintain their prolific blooming throughout the warmer months. While they’re most often grown as annuals, they can sometimes act as tender perennials in mild climates. Easy to grow and low-maintenance, petunias also help attract pollinators like bees and butterflies, adding life and movement to outdoor spaces. With their generous flowering habit and eye-catching beauty, petunias are a symbol of grace, creativity, and cheerful charm in any landscape.",
          "qty" : 1,
          "image": ["https://buchanansplants.com/wp-content/uploads/2021/09/Hurrah-Blue-Veined-Petunia.jpg", "https://plants.moananursery.com/Content/Images/Photos/L196-13.jpg", "https://cdn.britannica.com/89/131089-050-A4773446/flowers-garden-petunia.jpg"],
        },
        {
          "id": 17,
          "name": "Chrysanthemum",
          "price": 189,
          "rating": 2,
          "description": "The Chrysanthemum, affectionately known as the Queen of Autumn, is a beloved flowering plant admired for its rich colors, layered petals, and cultural symbolism. Belonging to the Asteraceae family, chrysanthemums are native to Asia and northeastern Europe, with deep roots in Chinese and Japanese traditions where they represent longevity, happiness, and nobility. These hardy perennials bloom in late summer through fall, showcasing an array of colors — from gold, orange, and red to soft pinks, purples, and whites — in striking forms that range from daisy-like singles to densely packed pompons. Chrysanthemums thrive in full sun, with well-drained soil and regular watering, rewarding gardeners with a vibrant burst of color when most other flowers begin to fade. Commonly used in floral arrangements, garlands, and festive decorations, they are also known for their role in natural pest control and herbal medicine. With their enduring beauty, symbolic depth, and seasonal charm, chrysanthemums bring both elegance and emotion to gardens, homes, and cultural celebrations alike.",
          "qty" : 9,
          "image": ["https://m.media-amazon.com/images/I/61d4pA8M9-L._SX679_.jpg", "https://m.media-amazon.com/images/I/61jMyONj2KL._SX679_.jpg", "https://m.media-amazon.com/images/I/61dxXrqAwqL.jpg"],
        },
        {
          "id": 18,
          "name": "Geranium",
          "price": 199,
          "rating": 2,
          "description": "The Geranium, a charming and versatile flowering plant, is known for its vibrant blooms, fragrant foliage, and wide-ranging adaptability. Belonging primarily to the Pelargonium genus (commonly referred to as geraniums in horticulture), these plants are native to southern Africa and have become global favorites for window boxes, balconies, borders, and containers. Their five-petaled flowers appear in a stunning array of colors — including red, pink, white, lavender, and orange — often blooming continuously through the warmer months. Many varieties also feature decorative, aromatic leaves with ruffled or zoned patterns, adding textural interest to any display. Geraniums prefer full sunlight, moderate watering, and well-draining soil, and they are valued for their drought tolerance and ease of care. Beyond their ornamental appeal, scented-leaf geraniums are also used in natural oils and insect repellents. Whether trailing from a hanging basket or brightening a sunny patio, the geranium combines resilience, beauty, and a touch of old-fashioned charm, making it a timeless favorite in gardens around the world.",
          "qty" : 0,
          "image": ["https://5.imimg.com/data5/ECOM/Default/2023/6/318852848/MJ/GS/RW/133331885/geranium-ivy-imperial-burgundy12-35855.jpg", "https://5.imimg.com/data5/ECOM/Default/2023/6/318852850/NY/YK/UH/133331885/f247d4.jpg", "https://www.syngentaflowers.com/ams/sites/g/files/kgtney2381/files/styles/flo_square_gallery_xl_2x/public/syngenta-flowers-pim/image/upload/v1750167929/70074807/na/70074807-pot.jpg.webp?itok=Po9WmoZn"],
        }
      ]
    },
    {
      "category": "Succulents",
      "plants": [
        {
          "id": 19,
          "name": "Aloe Vera",
          "price": 150,
          "rating": 5,
          "description": "The Aloe Vera plant, scientifically known as Aloe barbadensis miller, is a succulent marvel admired for both its soothing medicinal properties and its sculptural beauty. Native to the arid regions of the Arabian Peninsula but now grown worldwide, Aloe Vera features thick, fleshy, green to gray-green leaves that form a rosette and store a gel-like substance known for its cooling and healing effects. This hardy plant thrives in bright, indirect sunlight and well-drained, sandy soil, requiring minimal watering — making it an excellent choice for indoor pots, balconies, or xeriscape gardens. Beyond its decorative value, Aloe Vera is deeply valued in skincare and wellness, commonly used to treat burns, hydrate the skin, and aid in digestion. It also purifies indoor air, adding a fresh and calming presence to any space. With its minimal care needs and powerful natural benefits, Aloe Vera is both a practical and timeless addition to homes and herbal collections alike.",
          "qty" : 22,
          "image": ["https://rukminim2.flixcart.com/image/832/832/kzvlua80/plant-sapling/w/v/q/no-perennial-no-aloe-vera-popular-medicinal-plant-in-poly-1-original-imagbsz3ferjujhj.jpeg", "https://plants4presents.co.uk/media/catalog/product/cache/98624904c376a1958a1bd16e8bff50fa/a/l/aloeveralarge2023octoberlevelg.jpg", "https://m.media-amazon.com/images/I/514f8t4sNTL.jpg"],
        },
        {
          "id": 20,
          "name": "Jade Plant",
          "price": 180,
          "rating": 4,
          "description": "The Jade Plant, scientifically known as Crassula ovata, is a popular succulent celebrated for its thick, glossy leaves, tree-like structure, and association with prosperity and good fortune. Native to South Africa and Mozambique, this hardy plant has become a favorite in homes and offices worldwide, often referred to as the money plant or lucky plant in feng shui traditions. Its fleshy, oval-shaped leaves range from rich green to slightly reddish at the edges when exposed to sunlight, and mature plants may produce delicate clusters of star-shaped white or pink flowers in ideal conditions. The jade plant thrives in bright, indirect light and requires minimal watering, preferring dry spells between waterings — a hallmark of its drought-tolerant nature. Easy to propagate and long-lived, it grows slowly but steadily, often developing a bonsai-like appearance over time. Whether placed on a sunny windowsill or as a symbolic centerpiece, the jade plant brings a sense of serenity, longevity, and natural elegance to any indoor space.",
          "qty" : 28,
          "image": ["https://m.media-amazon.com/images/I/51n0fa4c-iL.jpg", "https://m.media-amazon.com/images/I/51n0fa4c-iL.jpg", "https://hips.hearstapps.com/hmg-prod/images/beautiful-crassula-ovata-jade-plant-money-plant-royalty-free-image-1722349156.jpg"],
        },
        {
          "id": 21,
          "name": "Echeveria",
          "price": 220,
          "rating": 2,
          "description": "The Echeveria is a striking and sculptural succulent known for its perfectly symmetrical rosettes and pastel-toned foliage. Native to semi-desert regions of Central America, Mexico, and northwestern South America, Echeverias belong to the Crassulaceae family and are adored for their compact size, geometric beauty, and wide variety of colors — from soft green and silvery blue to rose pink and lavender. Each fleshy leaf forms part of a tight rosette, and some varieties may produce tall flowering stalks with bell-shaped blooms in shades of coral, yellow, or orange. Echeverias thrive in full sun to bright indirect light and require very little water, making them ideal for drought-tolerant gardens, rockeries, or minimalist indoor displays. With excellent drainage, they flourish in containers and terrariums, adding a modern, low-maintenance touch to any setting. Beyond their visual appeal, Echeverias symbolize endurance and timeless beauty, making them a favorite among succulent lovers and plant stylists alike.",
          "qty" : 38,
          "image": ["https://i.etsystatic.com/10267921/r/il/d9fb66/5381152342/il_1588xN.5381152342_jgl4.jpg", "https://www.succulentplant.in/wp-content/uploads/2019/10/150S17.jpeg", "https://www.picturethisai.com/image-handle/website_cmsname/image/1080/153653709186793500.jpeg"],
        },
        {
          "id": 22,
          "name": "Zebra Plant",
          "price": 160,
          "rating": 2,
          "description": "The Zebra Plant, commonly referring to Haworthiopsis attenuata (formerly Haworthia attenuata), is a striking, low-maintenance succulent admired for its bold texture and distinctive white-striped pattern. Native to South Africa, this compact plant gets its name from the horizontal white ridges that run across its dark green, pointed leaves, resembling the stripes of a zebra. The leaves grow in a rosette formation, making it a perfect accent piece for small spaces, windowsills, or modern terrariums. The Zebra Plant thrives in bright, indirect sunlight and requires minimal watering, making it ideal for beginner plant owners and busy lifestyles. Its drought-tolerant nature and slow growth mean it rarely outgrows its pot, and it can thrive for years with just occasional care. While it may produce delicate white flowers on tall stalks during its blooming season, it’s the bold foliage that steals the show. With its sculptural appeal and easygoing temperament, the Zebra Plant brings a touch of the desert’s rugged charm into any indoor setting.",
          "qty" : 29,
          "image": ["https://greenparadiselive.com/cdn/shop/files/ORDER_haworthia_2.png", "https://ashiyanastore.com/cdn/shop/files/rn-image_picker_lib_temp_3b5971df-9042-4b78-9b77-d40d4829b743.jpg", "https://i.etsystatic.com/34288770/r/il/e288e9/4640414220/il_1588xN.4640414220_53eg.jpg"],
        },
        {
          "id": 23,
          "name": "String of Pearls",
          "price": 250,
          "rating": 3,
          "description": "The String of Pearls, scientifically known as Senecio rowleyanus, is a captivating trailing succulent admired for its unique, bead-like foliage and cascading beauty. Native to the arid regions of southwest Africa, this plant features long, slender stems adorned with perfectly spherical, green “pearls” that resemble a strand of delicate jewelry. These plump leaves are specially adapted to retain water, making the plant both charming and drought-tolerant. Ideal for hanging baskets, shelves, or high ledges, the String of Pearls thrives in bright, indirect light and requires infrequent watering, especially in cooler months. With the right care, it may even produce tiny, cinnamon-scented white flowers during its blooming season. Despite its delicate appearance, it’s relatively easy to maintain — though mildly toxic if ingested, so care is needed around pets and small children. Graceful, eye-catching, and a favorite among succulent enthusiasts, the String of Pearls adds a whimsical and modern touch to any indoor plant collection.",
          "qty" : 0,
          "image": ["https://cdn.shopify.com/s/files/1/0550/4771/6948/files/3.png", "https://planetdesert.com/cdn/shop/files/String-of-Pearls-_Senecio-rowleyanus_-2-Gallon-shop_63d86627-3d10-41ed-b1f1-234e1e2b55cc.jpg", "https://m.media-amazon.com/images/I/81s7V7gdcUL._SL1500_.jpg"],
        },
        {
          "id": 24,
          "name": "Sedum",
          "price": 130,
          "rating": 5,
          "description": "Sedum, also known as stonecrop, is a diverse genus of hardy succulents admired for their fleshy foliage, resilience, and vibrant seasonal blooms. Belonging to the Crassulaceae family, sedums are native to regions across the Northern Hemisphere and come in a wide range of forms — from low-growing ground covers to upright, bushy varieties. Their thick, water-storing leaves range in color from bright green and silvery blue to burgundy and gold, often forming beautiful rosettes or trailing mats. Sedums thrive in full sun, require minimal watering, and prefer well-drained soil, making them ideal for rock gardens, borders, green roofs, and drought-tolerant landscaping. During late summer to early fall, many varieties burst into star-shaped clusters of pink, red, or yellow flowers that attract pollinators like bees and butterflies. Exceptionally easy to grow and propagate, sedums are also popular in container arrangements and mixed succulent displays. With their tough nature, colorful variety, and year-round appeal, sedums are a gardener’s go-to for effortless beauty and texture.",
          "qty" : 18,
          "image": ["https://theaffordableorganicstore.com/cdn/shop/files/Untitleddesign42.webp", "https://www.lulasgarden.com/cdn/shop/articles/Care_Sedum_928x450_crop_center.jpg", "https://littleprinceplants.com/wp-content/uploads/2020/10/Sedum-palmeri-March2.jpg.webp"],
        }
      ]
    },
    {
      "category": "Herbs",
      "plants": [
        {
          "id": 25,
          "name": "Basil",
          "price": 99,
          "rating": 5,
          "description": "The Basil plant, scientifically known as Ocimum basilicum, is a fragrant, fast-growing herb cherished for its lush green leaves, culinary versatility, and cultural significance. Native to tropical regions of Asia and Africa, basil has been cultivated for centuries and holds a prominent place in cuisines around the world — from Italian pasta sauces to Thai curries and Indian herbal infusions. Its tender, aromatic leaves grow on upright stems and emit a sweet, peppery scent that intensifies in the sun. Basil thrives in warm weather, full sunlight, and well-drained soil, and it responds well to regular pinching, which encourages fuller growth and delays flowering. While the most common variety is sweet basil, others like Thai basil, lemon basil, and holy basil (Tulsi) each offer unique flavors and uses. In addition to its culinary charm, basil has natural antibacterial and anti-inflammatory properties, and is often used in traditional remedies. Whether grown in a kitchen garden or a sunny windowsill, basil brings together flavor, fragrance, and wellness in one vibrant green package.",
          "qty" : 33,
          "image": ["https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/Basil-Basilico-Ocimum_basilicum-albahaca.jpg/2560px-Basil-Basilico-Ocimum_basilicum-albahaca.jpg", "https://i0.wp.com/cdn-prod.medicalnewstoday.com/content/images/articles/266/266425/basil-in-a-bowel-on-a-table.jpg", "https://organicbazar.net/cdn/shop/products/Basil-Large-leaf-Seeds.jpg"],
        },
        {
          "id": 26,
          "name": "Mint",
          "price": 89,
          "rating": 1,
          "description": "The Mint plant, belonging to the Mentha genus, is a fast-growing, aromatic herb celebrated for its refreshing fragrance, cooling flavor, and medicinal qualities. Native to Europe and Asia, mint has become a staple in herb gardens and kitchens around the world, with popular varieties including spearmint (Mentha spicata) and peppermint (Mentha × piperita). Its bright green, serrated leaves release a crisp, invigorating scent when crushed and are used in everything from teas and chutneys to desserts and home remedies. Mint thrives in full to partial sunlight and moist, well-drained soil, though it spreads vigorously — often requiring containment in pots or bordered beds to keep it under control. Valued not only for its culinary versatility but also for its digestive, antibacterial, and soothing properties, mint is a go-to herb for both chefs and natural healers. Easy to grow and quick to regenerate after harvesting, the mint plant brings a burst of freshness, vitality, and timeless utility to gardens and windowsills alike.",
          "qty" : 0,
          "image": ["https://seedfella.com/cdn/shop/files/61YHNoyGe4L._AC_UF1000_1000_QL80_-Copy-Copy_b790e195-1f99-4c30-b2d8-e8e9eed4d8d2.jpg", "https://seedfella.com/cdn/shop/files/500-peppermint-seeds-herb-m444pp-500seeds-fourganic-original-imagkr3d7hztwu5h_9b01907a-033f-4ac3-a5b0-09c8c05eb473.webp", "https://dukaan.b-cdn.net/700x700/webp/upload_file_service/56dd9524-af8f-4194-9f06-828eec12244c/t-pudiinaa-kaa-paudhaa-herbal-medicinal-plant.png"],
        },
        {
          "id": 27,
          "name": "Coriander",
          "price": 79,
          "rating": 4,
          "description": "The Coriander plant, also known as Coriandrum sativum, is a fragrant and fast-growing herb treasured for its culinary versatility and fresh, citrusy aroma. Native to regions spanning Southern Europe, Northern Africa, and Southwestern Asia, coriander is cultivated globally and valued for both its leaves (known as cilantro) and seeds, which are used as a spice. The plant features delicate, lacy green foliage and slender stems that thrive in cool to moderate climates, preferring full sunlight and well-drained soil. Its leaves are a staple in Indian, Middle Eastern, Latin American, and Southeast Asian cuisines, adding a burst of freshness to curries, chutneys, salads, and soups. As the plant matures, it produces tiny white or pale pink flowers, which later turn into round, aromatic seeds with warm, nutty, and citrusy notes. In addition to its culinary use, coriander offers digestive and anti-inflammatory benefits in traditional medicine. Quick to grow and easy to harvest, coriander is a must-have herb for kitchen gardens, offering both flavor and function in one elegant plant.",
          "qty" : 22,
          "image": ["https://beejwala.com/cdn/shop/files/Coriander_F1_Hybrid_Seeds.webp", "https://images.immediate.co.uk/production/volatile/sites/10/2018/02/e0f2e690-693d-4539-a203-e5868d04309a-86ece10.jpg", "https://finediningindian.com/wp-content/uploads/2017/05/cilantro-1287301_1920-min.jpg"],
        },
        {
          "id": 28,
          "name": "Thyme",
          "price": 149,
          "rating": 2,
          "description": "The Thyme plant, botanically known as Thymus vulgaris, is a low-growing, aromatic herb cherished for its earthy fragrance, culinary uses, and medicinal qualities. Native to the Mediterranean region, thyme has long been a staple in herb gardens and kitchens, known for its small, oval-shaped gray-green leaves and delicate purple or pink flowers that bloom in summer. Its compact, bushy growth makes it ideal for edging, container planting, or even creeping between stepping stones in sunny gardens. Thriving in full sunlight and well-drained, slightly dry soil, thyme is remarkably hardy, drought-tolerant, and easy to care for. The leaves release a warm, savory scent and are used fresh or dried in a variety of dishes, especially in Mediterranean and French cuisine — pairing beautifully with roasted vegetables, meats, and soups. Beyond the kitchen, thyme has antiseptic and antioxidant properties, and is often used in teas, oils, and natural remedies. Elegant, fragrant, and enduring, thyme is both a practical and timeless herb that enriches both food and garden.",
          "qty" : 0,
          "image": ["https://www.thespruce.com/thmb/g-kH5hWIDhDAICOMsUARRUFGat0=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/how-to-grow-thyme-1402630-hero-d44ccea3e3604c1db97d23761b25de52.jpg", "https://urbantilth.org/wp-content/uploads/2021/10/thyme-1-scaled.jpeg", "https://nurserynisarga.in/wp-content/uploads/2022/03/thyme-herb.webp"],
        },
        {
          "id": 29,
          "name": "Oregano",
          "price": 139,
          "rating": 1,
          "description": "The Oregano plant, scientifically known as Origanum vulgare, is a flavorful, aromatic herb cherished for its bold taste, rich fragrance, and versatility in both culinary and medicinal traditions. Native to the Mediterranean region, oregano belongs to the mint family (Lamiaceae) and is a staple in Italian, Greek, and Middle Eastern cuisines. Its small, oval-shaped green leaves grow densely on woody stems and release a warm, peppery aroma when touched or crushed. Oregano thrives in full sun and well-drained soil, and once established, it is highly drought-tolerant, making it a perfect addition to herb gardens, rockeries, and container arrangements. During summer, it produces tiny purple or pink flowers that attract bees and other pollinators. The leaves can be used fresh or dried and are often added to pizzas, sauces, marinades, and roasted vegetables for a robust herbal kick. In traditional medicine, oregano is valued for its antibacterial, anti-inflammatory, and antioxidant properties. Hardy, easy to grow, and packed with character, oregano brings both flavor and resilience to any garden or kitchen.",
          "qty" : 47,
          "image": ["https://www.bhg.com/thmb/SFIicTy3R9Yj3EchiMu7iMNrfb4=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/BHG-102116352-CcU979pS4IN8kexqa0z0at-d3a98adfa6524e14882b4646d0169025.jpg", "https://www.kitchengardenplantcentre.co.uk/storage/img/products/oregano.webp", "https://organicbazar.net/cdn/shop/products/Untitled-design-2022-06-05T133315.189.jpg"],
        },
        {
          "id": 30,
          "name": "Lemongrass",
          "price": 119,
          "rating": 5,
          "description": "The Lemongrass plant, scientifically known as Cymbopogon citratus, is a tall, aromatic grass prized for its fresh citrus scent, culinary applications, and therapeutic properties. Native to tropical regions of Asia, lemongrass grows in dense clumps with slender, blade-like leaves and sturdy stalks that emit a zesty lemon fragrance when crushed. It thrives in full sun, rich, well-drained soil, and warm, humid climates, making it ideal for kitchen gardens, herb borders, and large pots. In cooking, lemongrass is a key ingredient in Southeast Asian cuisines, especially Thai, Vietnamese, and Indian dishes — adding a bright, tangy flavor to soups, curries, teas, and marinades. Beyond its culinary value, lemongrass is used in herbal remedies and essential oils for its calming, antimicrobial, and digestive benefits. Fast-growing and low-maintenance, lemongrass also naturally repels mosquitoes, making it a useful addition to outdoor spaces. With its graceful form, uplifting aroma, and multi-purpose nature, lemongrass is both a sensory delight and a practical plant for everyday living.",
          "qty" : 0,
          "image": ["https://www.thespruce.com/thmb/terkj0FX5jwnITmBGYeY9liPlv0=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/GettyImages-4871735521-05f50c5058b64d45b7d2ba8b9084dbb4.jpg", "https://mainaamgarden.com/cdn/shop/files/MotivationalInstagramPost_1080x1080px_32.png", "https://m.media-amazon.com/images/I/716ZkSsNJWL.jpg"],
        }
      ]
    }
  ]